allow-uncaught: false
async-only: false
bail: false
check-leaks: false
color: true
delay: false
diff: true
exit: false
extension: ['ts']
fail-zero: true
forbid-only: false
forbid-pending: false
full-trace: false
growl: false
ignore:
  - './prisma/'
  - './_build/'
  - './node_modules/'
inline-diffs: false
jobs: 1
node-option:
  - 'unhandled-rejections=strict'
require: 'ts-node/register'
package: './package.json'
# parallel: true
recursive: false
reporter: 'spec'
retries: 1
slow: 75
sort: false
spec:
  - 'tests/unit/**/*.spec.ts'
timeout: 2000
trace-warnings: true
ui: 'bdd'
v8-stack-trace-limit: 100
watch: false
watch-files:
  - './src/**/*.ts'
  - './tests/unit/**/*.spec.ts'
files:
  - './tests/unit/**/*.spec.ts'
